import sqlite3
import pandas as pd
import json
import os
from langchain.tools import tool

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'enterprise_data.db')
INSIGHTS_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'ml_insights.json')

@tool
def query_db(query: str) -> str:
    """Execute a SQL query against the enterprise customer database.
    
    The main table is 'customer_metrics'. 
    Columns: customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, 
    MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, 
    StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn.
    """
    try:
        conn = sqlite3.connect(DB_PATH)
        df = pd.read_sql(query, conn)
        conn.close()
        return df.to_json(orient='records')
    except Exception as e:
        return f"Error executing query: {str(e)}"

@tool
def get_ml_insights() -> str:
    """Retrieve the latest structured insights generated by the ML pipeline (churn risk, feature importance)."""
    try:
        if os.path.exists(INSIGHTS_PATH):
            with open(INSIGHTS_PATH, 'r') as f:
                return f.read()
        return "No ML insights available yet. Please run the ML pipeline."
    except Exception as e:
        return f"Error reading insights: {str(e)}"

@tool
def get_company_policy(topic: str) -> str:
    """Search for company policies related to a specific topic (e.g., 'pricing', 'retention')."""
    # Mock policies for the Telco use case
    policies = {
        "pricing": "Standard Fiber Optic pricing is $70-100/mo. New customers get $10 off for 12 months.",
        "retention": "High-risk customers with tenure > 2 years should be offered a 15% loyalty discount on 1-year contracts.",
        "support": "Tech Support is free for Fiber customers. DSL customers pay $5/mo unless part of a bundle."
    }
    return policies.get(topic.lower(), "No specific policy found for this topic.")
