import sqlite3
import pandas as pd
import json
import os
from langchain.tools import tool

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'enterprise_data.db')
INSIGHTS_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'ml_insights.json')

@tool
def query_db(query: str) -> str:
    """Execute a SQL query against the enterprise customer database and return the results as a string."""
    try:
        conn = sqlite3.connect(DB_PATH)
        df = pd.read_sql(query, conn)
        conn.close()
        return df.to_json(orient='records')
    except Exception as e:
        return f"Error executing query: {str(e)}"

@tool
def get_ml_insights() -> str:
    """Retrieve the latest structured insights generated by the ML pipeline."""
    try:
        if os.path.exists(INSIGHTS_PATH):
            with open(INSIGHTS_PATH, 'r') as f:
                return f.read()
        return "No ML insights available yet."
    except Exception as e:
        return f"Error reading insights: {str(e)}"

@tool
def get_company_policy(topic: str) -> str:
    """Search for company policies related to a specific topic (e.g., 'pricing', 'retention')."""
    # Simply returning mock data for now, but this could be a vector search call.
    policies = {
        "pricing": "Our current pricing policy for North region includes a 10% premium surcharge due to logistics.",
        "retention": "High-ticket customers (> $4000/mo) should be offered a 15% discount if they show churn signals.",
        "support": "Support response time target is < 2 hours for Gold tier customers."
    }
    return policies.get(topic.lower(), "No specific policy found for this topic.")
